name: freight-man-pages
on: [push, pull_request]
jobs:
  generate-manpages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run:  >-
          sudo apt-get update

          sudo apt-get install -y
          ronn

      - name: Generate manpages
        run: make man
